name: Run partitioned-heat-acceleration experiments
on: workflow_dispatch

jobs:
  run_experiments:
    strategy:
      matrix:
        experiment:
        - name: Table 6.1 QN-SC
          args: ' -o acceleration-studies/QN-SC.csv'
        - name: Table 6.1 rQN-WI
          args: '--exchange-substeps -o acceleration-studies/rQN-WI.csv'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./partitioned-heat-conduction
    container: precice/precice:nightly
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: |
          apt-get -qq update
          apt-get -qq install software-properties-common python3-dev python3-pip python3.12-venv git apt-utils pkg-config
          add-apt-repository -y ppa:fenics-packages/fenics
          apt-get -qq install --no-install-recommends fenics
          rm -rf /var/lib/apt/lists/*
      - name: Create venv
        run: |
          ./make-venv.sh
      - name: Activate venv
        # see https://stackoverflow.com/a/74669486
        run: |
          . .venv/bin/activate
          echo PATH=$PATH >> $GITHUB_ENV
      - name: Run tutorial
        run: |
          python3 doAccelerationStudy.py precice-config-rQNWI-template.xml --silent --executor Github ${{matrix.experiment.args}}
      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: partitioned-heat-conduction-acceleration ${{ matrix.experiment.name }}
          path: |
            # working directory is ignored by actions/upload-artifact
            ./partitioned-heat-conduction/acceleration-studies
  merge:
    runs-on: ubuntu-latest
    needs: run_experiments
    steps:
      - name: Merge results
        uses: actions/upload-artifact/merge@v4
        with:
          name: partitioned-heat-conduction-acceleration
