name: Publish docker base image
on:
  workflow_dispatch:

jobs:
  build_dealii_openfoam:
    name: "Build deal.ii-OpenFOAM"
    runs-on: ubuntu-latest
    env:
        docker_username: benjaminrodenberg
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.docker_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Dockerfile
        uses: docker/build-push-action@v6
        with:
          push: true
          file: "./tools/docker/dealii-openfoam/Dockerfile"
          tags: ${{ env.docker_username }}/dealii-openfoam:3.2.0rc1
  build_fenics_openfoam:
    name: "Build FEniCS-OpenFOAM"
    runs-on: ubuntu-latest
    env:
        docker_username: benjaminrodenberg
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ env.docker_username }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Dockerfile
        uses: docker/build-push-action@v6
        with:
          push: true
          file: "./tools/docker/fenics-openfoam/Dockerfile"
          tags: ${{ env.docker_username }}/fenics-openfoam:3.2.0rc1
