name: Run turek-hron-fsi3 experiments
on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  run_experiments:
    strategy:
      matrix:
        experiment:
        - name: Figure 6.8 FEniCS-OpenFOAM legacy
          solid-participant: fenics
          solid-run: run_legacy.sh
          container: benjaminrodenberg/fenics-openfoam
          id: legacy
          expects-error: true
        - name: Figure 6.8 FEniCS-OpenFOAM WI
          solid-participant: fenics
          solid-run: run_WI.sh
          container: benjaminrodenberg/fenics-openfoam
          id: WI
          expects-error: false
        - name: Figure 6.8 deal.II-OpenFOAM nonlin
          solid-participant: dealii
          solid-run: run.sh -e=/dealii-adapter/elasticity
          container: benjaminrodenberg/dealii-openfoam
          id: nonlin
          expects-error: false
    # runs-on: ubuntu-latest
    runs-on: self-hosted
    timeout-minutes: 4320
    defaults:
      run:
        shell: bash
        working-directory: ./turek-hron-fsi3
    container: ${{ matrix.experiment.container }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Activate OpenFOAM # From https://github.com/gerlero/setup-openfoam/blob/68e0bf96c7f2aac1a100291a5d61fff934a472a8/action.yml#L54-L69
        run: |
          old_path="$PATH"
          source /usr/lib/openfoam/openfoam2412/etc/bashrc || true

          for var in "${!WM_@}"; do
            echo "$var=${!var}" >> "$GITHUB_ENV"
          done

          for var in "${!FOAM_@}"; do
            echo "$var=${!var}" >> "$GITHUB_ENV"
          done

          echo "LD_LIBRARY_PATH=$LD_LIBRARY_PATH" >> "$GITHUB_ENV"

          echo "${PATH/%:$old_path}" >> "$GITHUB_PATH"
      - name: Install Dependencies
        run: |
          apt-get -qq update
          apt-get -qq install python3-dev python3-pip python3-venv git apt-utils pkg-config
          rm -rf /var/lib/apt/lists/*
      - name: Run tutorial
        continue-on-error: ${{ matrix.experiment.expects-error }}
        run: |
            # start two processes in parallel
            # 1) solid participant and
            # 2) fluid participant (OpenFOAM must not be run as root!)
            ./prep_${{ matrix.experiment.solid-participant }}.sh
            ( 
              cd ./solid-${{ matrix.experiment.solid-participant }} &&
              ./${{ matrix.experiment.solid-run }}
            ) &
            (
              chown -R precice . &&
              cd ./fluid-openfoam && 
              su precice -c 'source /usr/lib/openfoam/openfoam2412/etc/bashrc && ./run.sh'
            )
      - name: Copy results to correct folder
        if: always()
        run: cp ./solid-${{ matrix.experiment.solid-participant }}/precice-Solid-watchpoint-Flap-Tip.log ./studies/precice-Solid-watchpoint-Flap-Tip-${{ matrix.experiment.id }}.log
      - name: Create file with reduced results (filter times < 2.5e-1 and times > 3.5e-1)
        if: always()
        run: |
          cp ./studies/precice-Solid-watchpoint-Flap-Tip-${{ matrix.experiment.id }}.log ./studies/precice-Solid-watchpoint-Flap-Tip-${{ matrix.experiment.id }}-detail.log
          sed -i '2,251d' ./studies/precice-Solid-watchpoint-Flap-Tip-${{ matrix.experiment.id }}-detail.log
          sed -i '103,$d' ./studies/precice-Solid-watchpoint-Flap-Tip-${{ matrix.experiment.id }}-detail.log
      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: turek-hron-fsi3 ${{ matrix.experiment.name }}
          path: |
            # working directory is ignored by actions/upload-artifact
            ./turek-hron-fsi3/studies
  merge:
    runs-on: ubuntu-latest
    needs: run_experiments
    steps:
      - name: Merge results
        uses: actions/upload-artifact/merge@v4
        with:
          name: turek-hron-fsi3
